
// SIGNUP
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

// LOGIN
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// PROFILE UPDATE
export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_RESPONSE = 'PROFILE_UPDATE_RESPONSE';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';

export const SEND_SMS_REQUEST = 'SEND_SMS_REQUEST';
export const SEND_SMS_RESPONSE  = 'SEND_SMS_RESPONSE ';
export const SEND_SMS_FAILURE = 'SEND_SMS_FAILURE';


//LOGOUT
export const LOGOUT = 'LOGOUT';
