export const CART_ITEMS_LIST_REQUEST = "CART_ITEMS_LIST_REQUEST";
export const CART_ITEMS_LIST_RESPONSE = "CART_ITEMS_LIST_RESPONSE ";
export const CART_ITEMS_LIST_FAILURE = "CART_ITEMS_LIST_FAILURE";
